language: r

os: linux
dist: xenial

r:
  - oldrel
  - release
  - devel

cache: packages
warnings_are_errors: false

r_packages:
  - roxygen2
  - testthat
  - proto

apt_packages:
  - libudunits2-dev
  - libv8-dev
  - libgdal1-dev
  - libproj-dev
  - libgeos-dev
  - libjq-dev
  - libprotobuf-dev
  - protobuf-compiler
