language: r

r:
  - oldrel
  - release
  - devel

cache: packages
sudo: false
warnings_are_errors: false

r_packages:
  - roxygen2
  - testthat
  
r_github_packages: 
  - thomasp85/patchwork

apt_packages:
  - libudunits2-dev
  - libv8-dev
  - libgdal1-dev
  - libproj-dev
  - libgeos-dev
  - libjq-dev
  - libprotobuf-dev
  - protobuf-compiler
