#' Simulated CPUE data
#'
#' Simulated catch of lobsters per pot from 2000 to 2017, with changing
#' seasonal, depth, and soak-time coverage.
#' All values are generated by the deterministic simulator in
#' `data-raw/compact-brms-fixtures.R`; no commercial fishing records are
#' included.
#'
#' @format A data frame with one row per simulated pot lift and five columns:
#' \describe{
#'   \item{lobsters}{Number of lobsters caught in one pot.}
#'   \item{year}{Factor identifying fishing year, from 2000 to 2017.}
#'   \item{month}{Two-digit factor identifying calendar month.}
#'   \item{depth}{Fishing depth in metres.}
#'   \item{soak}{Pot soak time in hours.}
#'  }
#' @source Fully synthetic data generated for the package examples.
#'
"lobsters_per_pot"
